### PR TITLE
do not use group_names when not needed

### PR DESCRIPTION
**Pull request by vpiserchia**
Remove usage of group_names to be coherent with other install scripts

### CODE REVIEW

**Comment by amirhmoradi** [comment]
@vpiserchia I find your PR very useful, thanks for the great work. 
IMHO: It would be better and easier to validate a merge if different features where PR'ed separately. 

For example: 
PR1: renaming vars (proxy_port --> kasm_proxy_port...)
PR2: adding the single/multi install options
PR3: Moving install tasks around
PR4: changing the way group_names are identified
and so on.

Thanks.

**Comment by vpiserchia** [comment]
@amirhmoradi  I'll follow your instruction and this approach:

PR1: renaming vars (proxy_port --> kasm_proxy_port...)
PR2: adding the single/multi install options
PR3: Moving install tasks around
PR4: changing the way group_names are identified


For each of them I'll create a Issue to like the PR against. I hope this helps to track down the changes
br,
vito

**Comment by vpiserchia** [comment]
Following @amirhmoradi suggestion this PR will be closed in favor of more self-contained ones

**Comment by vpiserchia** [comment]
> Following @amirhmoradi suggestion this PR will be closed in favor of more self-contained ones

**Pull request closed without merging**
